### ISSUE TITLE
It cannot be installed in recent Moodle versions

### ISSUE THREAD

**Issue by mudrd8mz** [Uecki/lemo4moodle#3]
The plugin has this in version.php:
```
$plugin->supported = [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37];
```

However, that is not allowed syntax for this declaration. It must be an array of __two__ ascending integers as per the documentation (https://docs.moodle.org/dev/version.php).

So the correct value would be
```
$plugin->supported = [20, 37];
```

On that note, please note that in the plugins directory, you declare the plugin supports versions 3.8 and 3.9 too.

**Comment by Uecki** [comment]
Done, thanks for the correction.
