### ISSUE TITLE
Fatal SQL errors on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [Uecki/lemo4moodle#4]
As per https://docs.moodle.org/dev/Plugin_contribution_checklist#Cross-DB_compatibility Moodle plugins are expected to run on PostgreSQL as well as on MySQL at least. This block uses MySQL specific syntax and thence cannot be approved at the moment.

Let me suggest not to convert Unix timestamps to dates in SQL. Instead, use https://docs.moodle.org/dev/Time_API to display the times in the user's format and timezones.

![image](https://user-images.githubusercontent.com/85831/92968775-04179d80-f47c-11ea-99c4-3dd14809abbf.png)

**Comment by Uecki** [comment]
Thanks for the suggestion. It should now be implemented correctly and support PGSQL. The timestamp conversion is now done in php with help of the TIME API.
